version: '3.7'

services:
  database:
    container_name: database
    build: .
    ports:
      - 8080:8080
    depends_on:
      - delivery-pg

  delivery-pg:
    image: postgres:11
    container_name: delivery-pg
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=delivery_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
