version: '3.7'

services:
  delivery-db-pg:
    image: postgres:11
    container_name: delivery-db-pg
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=delivery_db
    hostname: localhost
    networks:
      - dev-network
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

services:
  delivery-backend:
    container_name: delivery-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=delivery-backend.docker
      - VIRTUAL_PORT=3000
    volumes:
      - ./src:/app/src
    expose:
      - "3000"
    networks:
      - dev-network

volumes:
  pgdata:
  
networks:
  dev-network:
