version: '3.7'

services:
  delivery-db-pg:
    image: postgres:11
    container_name: delivery-db-pg
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=delivery_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
